name: Primary testing workflow

on:
  workflow_call:
    inputs:
      os_list:
        description: 'JSON array of OS versions'
        required: true
        type: string
      python_list:
        description: 'JSON array of Python versions'
        required: true
        type: string

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os_list) }}
        python: ${{ fromJson(inputs.python_list) }}

    steps:
      - name: Set up environment
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e . pytest

      - name: Test import
        run: python -c "import dandi_compute_code"
